services:
  keydb:
    image: eqalpha/keydb:latest
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - nwsapi

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - nwsapi

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: "mongodb://root:root@mongo:27017/"
    depends_on:
      - mongo
    networks:
      - nwsapi

networks:
  nwsapi: